# Week 2 - Mini Assessment

Welcome to you mini assessment for week two. For this assessment, you will be completing 15 exercises where for each new exercise, the difficulty level will only increase. You've got this! 😎

At the end of an hour, we will walk over each question together. Feel free to post it on GitHub once you finish, under your respective folder for everything related to week 2.

1. import the numpy package and check its version.

In [ ]:
!pip install numpy 


You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np
np.__version__

'1.18.1'

2. Create an numpy range of values from 0 to 49 and name it `mynums`.

In [ ]:
mynums = np.arange(0, 50, dtype='int32')
mynums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int32)

3. Reshape the array you created in step 2 into a matrix with the shape below and assign a copy of it to a variable called `my_matrix`.

In [ ]:
print(mynums.shape) # (rows, columns)
my_matrix = mynums.reshape(5, 10)
len(my_matrix)

(50,)


5

In [ ]:
len(my_matrix)

5

4. Create a linearly-spaced array of size 100 between the numbers 20 to 100, assign it to the variable, `num_increases` and print it.

In [ ]:
num_increases = np.linspace(20, 100, num=100)
len(num_increases)
num_increases

array([ 20.        ,  20.80808081,  21.61616162,  22.42424242,
        23.23232323,  24.04040404,  24.84848485,  25.65656566,
        26.46464646,  27.27272727,  28.08080808,  28.88888889,
        29.6969697 ,  30.50505051,  31.31313131,  32.12121212,
        32.92929293,  33.73737374,  34.54545455,  35.35353535,
        36.16161616,  36.96969697,  37.77777778,  38.58585859,
        39.39393939,  40.2020202 ,  41.01010101,  41.81818182,
        42.62626263,  43.43434343,  44.24242424,  45.05050505,
        45.85858586,  46.66666667,  47.47474747,  48.28282828,
        49.09090909,  49.8989899 ,  50.70707071,  51.51515152,
        52.32323232,  53.13131313,  53.93939394,  54.74747475,
        55.55555556,  56.36363636,  57.17171717,  57.97979798,
        58.78787879,  59.5959596 ,  60.4040404 ,  61.21212121,
        62.02020202,  62.82828283,  63.63636364,  64.44444444,
        65.25252525,  66.06060606,  66.86868687,  67.67676768,
        68.48484848,  69.29292929,  70.1010101 ,  70.90

5. Create an numpy array with 20 zeros, assign it to the variable `zeroes`.

In [ ]:
zeroes = np.zeros(20, dtype='int8')
zeroes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [ ]:
len(zeroes)

20

6. Create a two dimensional array of size 7 by 8 filled with 1s and do the following:
- mulptiply the first row by 2
- add 3 and raise to the power of two the odd columns starting from the beginning
- subtract 10 and multiply by 15 the elements in the even rows and odd columns

In [ ]:
array1 = np.ones((7, 8), dtype='int32')
array1

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
matrix1 = array1.reshape(7, 8).copy()
matrix1

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
matrix2 = array1.reshape(7, 8).copy()
matrix2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

6. Create a two dimensional array of size 7 by 8 filled with 1s and do the following:
- mulptiply the first row by 2
- add 3 and raise to the power of two the odd columns starting from the beginning
- subtract 10 and multiply by 15 the elements in the even rows and odd columns


In [ ]:
#multiply the first row by 2
num12 = sum(matrix1[0,:])*2
num12

16

In [ ]:
arr = np.arange(30).reshape(5, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
new_arr = (arr[:, ::2] + 3) ** 2
new_arr

array([[  9,  25,  49],
       [ 81, 121, 169],
       [225, 289, 361],
       [441, 529, 625],
       [729, 841, 961]])

In [ ]:
#add 3 and raise to the power of two the odd columns starting from the beginning
new_arr = (matrix1[:, ::2] + 3) ** 2
new_arr

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]], dtype=int32)

In [ ]:
#subtract 10 and multiply by 5 the elements in the even rows and odd columns
new_arr2 = (matrix1[1:2, ::2] - 10) *5
new_arr2



array([[-45, -45, -45, -45]], dtype=int32)

7. Create a numpy array starting with 20 and ending with 40 with 10 equally spaced values.

In [ ]:
even = np.linspace(20, 40, num=10)
even

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])

8. Create a 9 by 9 matrix with random integers from 100 to 500 and use the dtype "int32".

In [ ]:
matrix3 = np.random.randint(low=0, high=100, size=81, dtype='int8').reshape(9,9)
matrix3

array([[46, 75, 13, 86, 46, 50, 66, 11, 51],
       [60, 34,  7,  1, 76, 40, 10, 92, 63],
       [30, 52, 86, 33, 90, 94, 56,  7, 84],
       [42, 84, 89, 41, 68, 55, 34, 13, 97],
       [83, 27, 65, 68, 75,  0, 96, 98, 10],
       [ 7, 86, 77, 29, 54,  2, 79, 33, 44],
       [ 4, 34, 66, 69, 21,  8, 36, 99, 81],
       [59, 53, 95, 27,  1, 30, 48,  8, 16],
       [97, 23, 82, 49,  9, 98, 95, 42, 94]], dtype=int8)

9. Create an empty array of 20 elements with shape 2 by 10, dtype 'float32' and add a different number to each row.

In [ ]:
matrix5 = np.empty((2, 10), dtype='float32').reshape(2,10)
matrix5[0]= 5
matrix5[1]=10
matrix5

array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]], dtype=float32)

10. Create an array with 15 random numbers between 100 and 200 and print the maximum value in the array.

In [ ]:
array3 = np.random.randint(low=100, high=200, size=15, dtype='int32')
print(f"Maximum Value: {np.max(array3)}")

Maximum Value: 194


11. Create an array with the following numbers [40, 41, 26, 14, 15, 47, 43, 33, 44, 22], select the 5th to 10th elements, assign each to a new variable, change their value, and then print all 3 (the first array and your next two variables.

In [11]:
array3 = np.array([40, 41, 26, 14, 15, 47, 43, 33,44,22])
array4 = array3[-5:]
array4[0]=55
array3
array4

array([55, 43, 33, 44, 22])

12. Create an array of 360 random numbers from -10 to 50 (to resemble the weather) and find the min, max, 25th percentile, 75 percentile, and the median.

In [14]:
weather = np.random.randint(low=-10, high=50, size=360, dtype='int32')
print(weather)
print(f"Minimum Value: {np.min(weather)}")
print(f"Maximum Value: {np.max(weather)}")
print(f"25th percentile: {np.percentile(weather, 25)}")
print(f"Median: {np.median(weather)}")
print(f"75th percentile: {np.percentile(weather, 75)}")


[ 12  14  -6  29  44  30  43   0  32  42  21  -3  28   7  -3  23  46  17
  -2  40   6  34  29  43  -4  -8  14  46  26  21  34   9  18  21  14  38
  14  49  -5  29  10  22   4  14   3  27  12  10  40  -8   5   5  -1  -1
  -2  -6  49   5  36  28  11  48  36   3  -7  -5  33  43  19 -10  46  10
  26  10   9  33  30   3  33  42   1  39  20  -3  20  43   7  49  32  -9
  32  -2  42  43  13 -10   5  38  28  36   3   2  10  46  23  10   0  30
  15  21  24  48  46  32   2  19  -6   5  -6  21  41  42  13  36  23  18
  16  46  14  28  46  24  18   9  41  47  45  30  15  30  24  -9  20  21
   3  -1  46  40  15   4  10  34  -7  13  26  -3   8  46  37  -1  -8  29
   4   8   4  28  19  46  21  45  12   8  -5  34  22  24  28  -2  33  35
   1  11  20  36  10  -4  -1  23  31  10  11  -4  43  -7  36  34  -3  16
  42   6  29  23  48  33   3  28  16  -6  19  18  48  45  16   2  11  32
  23  -5  46  -6  21  -5  32  20   2  48   5  -9  11  -5  17  19   8  14
  47  -9  -5  -7   5  22  23   8  31  32  49  16  -

13. Reshape the array you created in step 12 into a matrix of 300 by 12 ad get the same values but only for the months this time.

In [35]:
weatherM = weather.reshape(30,12)
print(weatherM)
print(f"Minimum Value: {np.min(weatherM,axis=0)}")
print(f"Maximum Value: {np.max(weatherM,axis=0)}")
print(f"25th percentile: {np.percentile(weatherM,25,axis=0)}")
print(f"Median: {np.median(weatherM,axis=0)}")
print(f"75th percentile: {np.percentile(weatherM,75,axis=0)}")


[[ 12  14  -6  29  44  30  43   0  32  42  21  -3]
 [ 28   7  -3  23  46  17  -2  40   6  34  29  43]
 [ -4  -8  14  46  26  21  34   9  18  21  14  38]
 [ 14  49  -5  29  10  22   4  14   3  27  12  10]
 [ 40  -8   5   5  -1  -1  -2  -6  49   5  36  28]
 [ 11  48  36   3  -7  -5  33  43  19 -10  46  10]
 [ 26  10   9  33  30   3  33  42   1  39  20  -3]
 [ 20  43   7  49  32  -9  32  -2  42  43  13 -10]
 [  5  38  28  36   3   2  10  46  23  10   0  30]
 [ 15  21  24  48  46  32   2  19  -6   5  -6  21]
 [ 41  42  13  36  23  18  16  46  14  28  46  24]
 [ 18   9  41  47  45  30  15  30  24  -9  20  21]
 [  3  -1  46  40  15   4  10  34  -7  13  26  -3]
 [  8  46  37  -1  -8  29   4   8   4  28  19  46]
 [ 21  45  12   8  -5  34  22  24  28  -2  33  35]
 [  1  11  20  36  10  -4  -1  23  31  10  11  -4]
 [ 43  -7  36  34  -3  16  42   6  29  23  48  33]
 [  3  28  16  -6  19  18  48  45  16   2  11  32]
 [ 23  -5  46  -6  21  -5  32  20   2  48   5  -9]
 [ 11  -5  17  19   8  14  47  

14. Create a mask for your data, and filter out and print:
- average temperature of the days where the temperature was below 10
- average temperature of the days where the temperature was greater than 30

In [28]:
bad_days_mask = (weatherM < 10)
bad_days_mask
bad_days = weatherM[bad_days_mask]
bad_days
print("The Average temperature on bad days was %i F ☀️" % np.mean(bad_days))

The Average temperature on bad days was 0 F ☀️


In [30]:
nice_days_mask = (weatherM > 10)
nice_days_mask
nice_days = weatherM[nice_days_mask]
nice_days
print("The Average temperature on nice days was %i F ☀️" % np.mean(nice_days))

The Average temperature on nice days was 30 F ☀️


15. Create a full 10 by 10 matrix with a number of your choosing and assign it to a variable. After printing that variables, unravel the matrix and assign the array to a new number.

In [32]:
array30 = np.random.randint(low=100, high=2000, size=100, dtype='int32').reshape(10,10)
print(array30)
array40 = array30.ravel().copy
print(array40)

[[ 949 1840  202  950 1424  301  816  150  250  385]
 [ 938 1413  965 1062  895  633 1971 1642  938 1229]
 [ 186 1916 1226  923 1512  953 1805 1053  627  269]
 [ 866  828 1520 1773  375  444 1466  812 1507 1015]
 [ 600  784  907 1881  157  635 1270  450  203 1343]
 [1259  876  865  707 1908 1254  100 1930 1558  998]
 [ 658  794  672 1220  773 1610  527 1688 1831 1868]
 [1136  998 1879 1304 1398 1731  543  147  247  915]
 [1858  370  995 1172 1131  961 1960 1051 1927 1786]
 [ 760 1824 1048 1130 1167  471  446 1082  399  556]]
<built-in method copy of numpy.ndarray object at 0x7f5aff515c60>
